version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_DATABASE=scheduling-management
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=1q2w3e4r@#$
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
    
volumes:
  sql_data: